"""Add Review Model

Revision ID: cda04f472b55
Revises: 362af71b1602
Create Date: 2023-09-13 23:08:13.255631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda04f472b55'
down_revision = '362af71b1602'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
